language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  # different connection classes to test
  - TEST_ES_CONNECTION=Urllib3HttpConnection
  - TEST_ES_CONNECTION=RequestsHttpConnection

before_install:
  - echo '\n' | sudo add-apt-repository ppa:webupd8team/java
  - sudo apt-get update
  - sudo apt-get install oracle-java8-installer oracle-java8-set-default
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - java -version

install:
  - wget -O /tmp/es-snap.zip "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.0.0.zip"
  - unzip /tmp/es-snap.zip -d /tmp/
  - mv /tmp/elasticsearch-5.0.0 /tmp/elasticsearch
  - /tmp/elasticsearch/bin/elasticsearch -E script.inline=true -E path.repo=/tmp -E repositories.url.allowed_urls='http://*' -E node.attr.testattr=test > temp.txt &
  - git clone https://github.com/elastic/elasticsearch.git ../elasticsearch
  - pip install .

script:
  - python setup.py test

after_failure:
  - cat temp.txt

notifications:
  email:
    recipients:
      - honza.kral@gmail.com
