language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

addons:
  apt:
    packages:
      - oracle-java8-installer

env:
  # different connection classes to test
  - TEST_ES_CONNECTION=Urllib3HttpConnection ES_VERSION=5.x
  - TEST_ES_CONNECTION=RequestsHttpConnection ES_VERSION=5.x

before_install:
  - sudo update-java-alternatives -s java-8-oracle
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle/jre
  - java -version

install:
  - export ES_URL=$(curl -sS "https://esvm-props.kibana.rocks/builds" | jq -r ".branches[\"$ES_VERSION\"].zip")
  - curl -L -o /tmp/es-snap.zip $ES_URL
  - unzip /tmp/es-snap.zip -d /tmp/
  - /tmp/elasticsearch-*/bin/elasticsearch -E script.inline=true -E path.repo=/tmp -E repositories.url.allowed_urls='http://*' -E node.attr.testattr=test -d
  - git clone https://github.com/elastic/elasticsearch.git ../elasticsearch
  - pip install .

script:
  - python setup.py test

after_failure:
  - cat /tmp/elasticsearch-*/logs/elasticsearch.log

notifications:
  email:
    recipients:
      - honza.kral@gmail.com
